name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DH_USERNAME }}
        password: ${{ secrets.DH_TOKEN }}
    - name: Clone Repo
      uses: actions/checkout@v2
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: arukaen/tautulli-docker
    - name: Build and Push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
